config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'users#index'
  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :new, :create, :show ] do
      resources :comments, only: [:new, :create ]
      resources :likes, only: [:new, :create ]
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :author, class_name: 'User',
                      foreign_key: 'author_id'
  belongs_to :post, counter_cache: :comments_count

  after_save :update_comments_count

  private

  def update_comments_count
    post.update(comments_count: post.comments.size)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :author, class_name: 'User',
                      foreign_key: 'author_id'
  belongs_to :post, counter_cache: :likes_count

  after_save :update_likes_count

  private

  def update_likes_count
    post.update(likes_count: post.likes.size)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, presence: true, length: { maximum: 250 }
  validates :likes_count, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :comments_count, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  belongs_to :author, class_name: 'User',
                      foreign_key: 'author_id',
                      counter_cache: :posts_counter
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  after_save :update_posts_count

  def most_recent_five_comments
    comments.includes(:user).order(created_at: :desc).limit(5)
  end

  private

  def update_posts_count
    author.update(posts_counter: author.posts.size)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  validates :name, presence: true
  validates :posts_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  has_many :posts, foreign_key: 'author_id', dependent: :destroy
  has_many :likes, foreign_key: 'author_id', dependent: :destroy
  has_many :comments, foreign_key: 'author_id', dependent: :destroy

  def most_recent_three_posts
    posts.includes(:user).order(created_at: :desc).limit(3)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :update_allowed_parameters, if: :devise_controller?

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password, :password_confirmation) }
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password) }
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new; end

  def create
    user = User.find(params[:user_id])
    post = Post.find(params[:post_id])
    text = params[:text]

    new_comment = Comment.new(text:, post:, author: current_user)

    if new_comment.save
      flash[:notice] = 'You have successfully added a new comment.'
      redirect_to user_post_url(user, post)
    else
      render :new
    end
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def new; end

  def create
    user = User.find(params[:user_id])
    post = Post.find(params[:post_id])

    new_like = Like.new(post:, author: current_user)

    if new_like.save
      flash[:notice] = 'You have successfully added a like.'
      redirect_to user_post_url(user, post)
    else
      render :new
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    author_id = params[:user_id]
    @user = User.find(author_id)
    @posts = @user.posts
  end

  def show
    id = params[:id]
    @post = Post.includes([:comments]).find(id)
  end

  def new; end

  def create
    user = current_user
    text = params[:text]
    title = params[:title]

    new_post = Post.new(title:, text:, author: user)

    if new_post.save
      flash[:notice] = 'You have successfully created a new post.'
      redirect_to user_post_url(user, new_post)
    else
      render :new
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @posts = @user.posts
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/new.html.erb
<div class="form">
  <%= form_with model: @comment, url: user_post_comments_url, method: :post do |form| %>
    <div class="form-group">
      <%= form.text_field :text, :placeholder=> "Text" %>
        <%= form.submit "Submit" %>
    </div>
    <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>RorBlogApp</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag "application" , "data-turbo-track": "reload" %>
</head>

<body>
  <main>
    <%= yield %>
  </main>

  <div>
    <% flash.each do |type, msg| %>
      <div class="alert alert-info">
        <%= msg %>
      </div>
    <% end %>
  </div>
</body>

</html>

app/views/likes/new.html.erb
<div class="form">
  <%= form_with model: @like, url: user_post_likes_path, method: :post do |form| %>
    <div class="form-group">
      <%= form.submit "Like" %>
    </div>
    <% end %>
</div>

app/views/posts/_post.html.erb
<%= link_to user_post_path(user, post) do %>
  <div class="post">
    <h2>
      <span>Post #<%= index %></span>
      <span>
        <%= post.title %>
      </span>
    </h2>
    <p>
      <%= post.text %>
    </p>
    <small>
      <span>Comment: <%= post.comments_count %>, Likes: <%= post.likes_count %></span>
    </small>
  </div>
<% end %>

app/views/posts/_post_details.html.erb
<div class="post">
  <div class="comment-header">
    <h2>
      Post by <%= post.author.name %>
    </h2>
    <small>
      <span>Comment: <%= post.comments_count %>, Likes: <%= post.likes_count %></span>
    </small>
  </div>
  <p>
    <%= post.text %>
  </p>
</div>

app/views/posts/index.html.erb
<div>
  <%= render partial: "users/user" , locals: { user: @user } %>
</div>

<div class="posts">
  <% @posts.each_with_index do |post, index| %>
    <%= render partial: "post" , locals: { user: @user, post: post, index: index } %>
      <ul>
        <% post.comments.each do |comment| %>
          <li>
            <%= render partial: "shared/comment" , locals: { comment: comment } %>
          </li>
          <% end %>
      </ul>
      <% end %>
</div>

app/views/posts/new.html.erb
<div class="form">
  <%= form_with model: @post, url: user_posts_url, method: :post do |form| %>
    <div class="form-group">
      <%= form.text_field :title, :placeholder=> "Title" %>
        <%= form.text_field :text, :placeholder=> "Text" %>
          <%= form.submit "Submit" %>
    </div>
    <% end %>
</div>

app/views/posts/show.html.erb
<div>
  <%= render partial: "post_details" , locals: { post: @post } %>
</div>
<div class="posts">
  <ul>
    <% @post.comments.each do |comment| %>
      <li>
        <%= render partial: "shared/comment" , locals: { comment: comment } %>
      </li>
      <% end %>
  </ul>
</div>

app/views/shared/_comment.html.erb
<span>
  <%= comment.author.name %>: <%= comment.text %>
</span>

app/views/users/_user.html.erb
<%= link_to user_path(user), class: 'user' do %>
  <div class="photo">
    <img alt="my photo" src="<%= user.photo %>" />
  </div>

  <div class="data">
    <h2>
      <%= user.name %>
    </h2>
    <small>
      <span>Number of posts: </span>
      <%= user.posts_counter %>
    </small>
  </div>
<% end %>

app/views/users/index.html.erb
<h1 style="margin: 1rem auto; text-align: center;">All users</h1>
<%= render @users %>

app/views/users/show.html.erb
<div class="users">
  <div>
    <%= render @user %>
  </div>

  <div class="user-bio">
    <h4>Bio</h4>
    <p>
      <%= @user.bio %>
    </p>
  </div>

  <div>
    <% @posts.each_with_index do |post, index| %>
      <%= render partial: "posts/post" , locals: { user: @user, post: post, index: index } %>
    <% end %>
  </div>

  <button type="button">
    <%= link_to "See all posts", user_posts_path(@user) %>
  </button>

  <%=form_with model: User.new, url: destroy_user_session_path, method: :delete do %>
    <button>Sign out</button>
  <% end %>
</div>